/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core

layout(local_size_x = 64, local_size_y = 1) in;

layout(set = 0, binding = 0) buffer writeonly BufOut {
    uint o[];
};
layout(set = 0, binding = 1) buffer readonly BufData {
    float v[];
};

void main() {
    uint ret = packHalf2x16(vec2(v[gl_LocalInvocationIndex], 0.));
    o[gl_LocalInvocationIndex] = ret;
}
/*
; BEGIN_SHADERTEST
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=CHECK %s

; CHECK-LABEL: {{^// LLPC}} final pipeline module info
; CHECK: %{{[0-9]+}} = call <2 x half> @llvm.amdgcn.cvt.pkrtz(float %{{[0-9]+}}, float 0.000000e+00)

; CHECK: AMDLLPC SUCCESS
; END_SHADERTEST
*/
