// RUN: amdllpc -v %gfxip %s | FileCheck %s

// CHECK-LABEL: {{^}}// LLPC final ELF info
// CHECK: v_max_f32_dpp {{.*}} quad_perm:[1,0,3,2] row_mask:0xf bank_mask:0xf bound_ctrl:1
// CHECK: v_mov_b32_dpp {{.*}} row_bcast:15 row_mask:0xa bank_mask:0xf bound_ctrl:1
// CHECK: v_mov_b32_dpp {{.*}} row_bcast:15 row_mask:0xa bank_mask:0xf bound_ctrl:1
// CHECK: v_max_f32_dpp {{.*}} quad_perm:[1,0,3,2] row_mask:0xf bank_mask:0xf bound_ctrl:1

#version 450
#extension GL_KHR_shader_subgroup_arithmetic : require
#extension GL_KHR_shader_subgroup_clustered : require

layout(set=0, binding=0) buffer Buf {
  float h[32];
} data;

void main() {
  float val = data.h[gl_SubgroupInvocationID];
  val = subgroupMax(val);
  val = subgroupInclusiveMax(val);
  val = subgroupExclusiveMax(val);
  val = subgroupClusteredMax(val, 32);
  data.h[gl_SubgroupInvocationID] = val;
}
