/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

// RUN: amdllpc -v %gfxip %s | FileCheck %s

// CHECK-LABEL: {{^}}// LLPC final ELF info
// CHECK: v_max_f32_dpp {{.*}} quad_perm:[1,0,3,2] row_mask:0xf bank_mask:0xf bound_ctrl:1
// CHECK: v_min_f32_dpp {{.*}} quad_perm:[2,3,0,1] row_mask:0xf bank_mask:0xf bound_ctrl:1

#version 450
#extension GL_KHR_shader_subgroup_quad : require

layout(set=0, binding=0) buffer Buf {
  float h[32];
} data;

void main() {
  float val = data.h[gl_SubgroupInvocationID];
  val = max(val, subgroupQuadSwapHorizontal(val));
  val = min(val, subgroupQuadSwapVertical(val));
  data.h[gl_SubgroupInvocationID] = val;
}
