#version 450 core

layout(set = 0, binding = 0, rgba8)          uniform image2D img1;
layout(set = 0, binding = 1, rgba8) restrict uniform image2D img2;
layout(set = 0, binding = 2, rgba8) coherent uniform image2D img3;
layout(set = 0, binding = 3, rgba8) volatile uniform image2D img4;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mOut;
};

void main()
{
    mOut  = imageLoad(img1,        ivec2(1, 1));
    mOut += imageLoad(img2,        ivec2(2, 2));
    mOut += imageLoad(img3,        ivec2(3, 3));
    mOut += imageLoad(img4,        ivec2(4, 4));
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 0
; SHADERTEST: call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.load.v4f32(i32 1, i32 512, <8 x i32> %{{[-0-9A-Za0z_.]+}}, <2 x i32> <i32 1, i32 1>)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 1
; SHADERTEST: call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.load.v4f32(i32 1, i32 512, <8 x i32> %{{[-0-9A-Za0z_.]+}}, <2 x i32> <i32 2, i32 2>)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 2
; SHADERTEST: call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.load.v4f32(i32 1, i32 513, <8 x i32> %{{[-0-9A-Za0z_.]+}}, <2 x i32> <i32 3, i32 3>)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 3
; SHADERTEST: call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.load.v4f32(i32 1, i32 515, <8 x i32> %{{[-0-9A-Za0z_.]+}}, <2 x i32> <i32 4, i32 4>)

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: call {{.*}} <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 1, i32 1,{{.*}}, i32 0, i32 0)
; SHADERTEST: call {{.*}} <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 2, i32 2,{{.*}}, i32 0, i32 0)
; SHADERTEST: call {{.*}} <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 3, i32 3, <8 x i32> %{{[-0-9A-Za0z_.]+}}, i32 0, i32 1)
; SHADERTEST: call {{.*}} <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 4, i32 4, <8 x i32> %{{[-0-9A-Za0z_.]+}}, i32 0, i32 1)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
