/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core

layout(set = 0, binding = 0, rgba8) uniform image2D img2D;
layout(set = 0, binding = 1, rgba8) uniform image1D img1D;
layout(set = 0, binding = 2, rgba8) uniform image3D img3D;
layout(set = 0, binding = 3, rgba8) uniform image1DArray img1DArray;
layout(set = 0, binding = 4, rgba8) uniform image2DArray img2DArray;
layout(set = 0, binding = 5, rgba8) uniform image2DRect img2DRect;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mIn;
};

void main()
{
    imageStore(img2D,        ivec2(0, 0), mIn);
    imageStore(img1D,        0, mIn);
    imageStore(img3D,        ivec3(0, 0, 0), mIn);
    imageStore(img1DArray,   ivec2(0, 0), mIn);
    imageStore(img2DArray,   ivec3(0, 0, 0), mIn);
    imageStore(img2DRect,    ivec2(0, 0), mIn);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
