/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core
#extension GL_AMD_shader_image_load_store_lod : enable

layout(set = 0, binding = 0,  r32i) uniform iimage1D        img1D;
layout(set = 0, binding = 1,  r32i) uniform iimage2D        img2D;
layout(set = 0, binding = 2,  r32i) uniform iimage3D        img3D;
layout(set = 0, binding = 3,  r32i) uniform iimageCube      imgCube;
layout(set = 0, binding = 4,  r32i) uniform iimage1DArray   img1DArray;
layout(set = 0, binding = 5,  r32i) uniform iimage2DArray   img2DArray;
layout(set = 0, binding = 6,  r32i) uniform iimageCubeArray imgCubeArray;

void main()
{
    ivec4 temp = ivec4(0);
    temp += imageLoadLodAMD(img1D,          9,              7);
    temp += imageLoadLodAMD(img2D,          ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img3D,          ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCube,        ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(img1DArray,     ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img2DArray,     ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7);

    imageStoreLodAMD(img1D,          9,              7, temp);
    imageStoreLodAMD(img2D,          ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img3D,          ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCube,        ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(img1DArray,     ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img2DArray,     ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7, temp);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  FE lowering results
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 6)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 5)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 4)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 3)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 2)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 1)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 0)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 0, i32 516, {{.*}}, i32 9, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 1, i32 516, {{.*}}, <2 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 2, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 3, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 4, i32 516, {{.*}}, <2 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 5, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 8, i32 516, {{.*}}, <4 x i32> <i32 9, i32 9, i32 3, i32 1>, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 0, i32 516, {{.*}}, i32 9, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 1, i32 516, {{.*}}, <2 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 2, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 3, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 4, i32 516, {{.*}}, <2 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 5, i32 516, {{.*}}, <3 x i32> {{(splat \(i32 9\))|(<i32 9, i32 9, i32 9>)}}, i32 7)
; SHADERTEST: call {{.*}} @lgc.create.image.store({{.*}}, i32 8, i32 516, {{.*}}, <4 x i32> <i32 9, i32 9, i32 3, i32 1>, i32 7)

; SHADERTEST-LABEL: LLPC LGC lowering results
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.1d.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.2d.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.3d.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.cube.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.1darray.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: call i32 @llvm.amdgcn.image.load.mip.2darray.i32.i16{{(\.v8i32)?}}(i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.1d.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.2d.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.3d.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.cube.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.1darray.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.2darray.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST:  call void @llvm.amdgcn.image.store.mip.cube.f32.i16{{(\.v8i32)?}}(float %{{.*}}, i32 1, i16 9, i16 9, i16 9, i16 7, <8 x i32> %{{.*}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
