#version 450 core

layout(set = 0, binding = 0, rgba8i)  uniform iimage2D img2Di;
layout(set = 0, binding = 1, rgba8ui) uniform uimage2D img2Du;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mOut;
};

void main()
{
    ivec4 temp1 = imageLoad(img2Di, ivec2(0, 0));
    uvec4 temp2 = imageLoad(img2Du, ivec2(0, 0));
    mOut = vec4(temp1 + temp2);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 0)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 1, i32 516, {{.*}}, <2 x i32> zeroinitializer)
; SHADERTEST: call {{.*}} @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 1)
; SHADERTEST: call {{.*}} @lgc.create.image.load.v4i32(i32 1, i32 512, {{.*}}, <2 x i32> zeroinitializer)

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: call <4 x i32> @llvm.amdgcn.image.load.2d.v4i32.i32(i32 15, i32 0, i32 0, <8 x i32> %{{[-0-9A-Za0z_.]+}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
