#version 450 core

layout(set = 0, binding = 0 ) uniform sampler2DMS       samp2DMS;
layout(set = 0, binding = 1 ) uniform sampler2DMSArray  samp2DMSA;

layout(set = 1, binding = 0) buffer BO
{
    int mOut;
};

void main()
{
    int temp = 0;

    temp += textureSamples(samp2DMS);
    temp += textureSamples(samp2DMSA);

    mOut = temp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: ptr addrspace(4) (...) @lgc.create.get.desc.ptr.p4{{.*}}(i32 1, i32 1, i64 0, i32 0)
; SHADERTEST: call i32 (...) @lgc.create.image.query.samples.i32(i32 6, i32 512,
; SHADERTEST: ptr addrspace(4) (...) @lgc.create.get.desc.ptr.p4{{.*}}(i32 1, i32 1, i64 0, i32 1)
; SHADERTEST: call i32 (...) @lgc.create.image.query.samples.i32(i32 7, i32 512,

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
