/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) buffer Buffers
{
    uvec3 test;
};

void main()
{
    test = gl_WorkGroupID;
}

// BEGIN_SWIZZLETEST
// RUN: amdllpc -v %gfxip %s  --thread-group-swizzle-mode=4x4 | FileCheck -check-prefix=SWIZZLETEST %s
// SWIZZLETEST-LABEL: {{^// LLPC}} LGC before-lowering results
// SWIZZLETEST: %{{[0-9]+}} = call <3 x i32> @lgc.swizzle.workgroup.id(<3 x i32> %{{[0-9]+}}, <3 x i32> %{{[0-9]+}})
// SWIZZLETEST-LABEL: {{^// LLPC}} LGC lowering results
// SWIZZLETEST: .performSwizzle{{.*}}:
// SWIZZLETEST: AMDLLPC SUCCESS
// END_SWIZZLETEST
// BEGIN_NOTSWIZZLETEST
// RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=NOTSWIZZLETEST %s
// NOTSWIZZLETEST-LABEL: {{^// LLPC}} LGC before-lowering results
// NOTSWIZZLETEST-NOT: lgc.swizzle.workgroup.id
// NOTSWIZZLETEST-LABEL: {{^// LLPC}} LGC lowering results
// NOTSWIZZLETEST-NOT: .performSwizzle{{.*}}:
// NOTSWIZZLETEST: AMDLLPC SUCCESS
// END_NOTSWIZZLETEST
