/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0) buffer Buffers
{
    uvec3 test;
};

void main()
{
    test = gl_WorkGroupID;
}

// BEGIN_REVERSETEST
// RUN: amdllpc -v %gfxip %s --reverse-thread-group=1 --print-after=lgc-lower-desc 2>&1 | FileCheck -check-prefix=REVERSETEST %s
// REVERSETEST-LABEL: {{^// LLPC}} LGC before-lowering results
// There should be a calls to:
//  - get the descriptor table containing the buffer descriptor
//  - get the gl_NumWorkGroups
//  - get the internal descriptor table
// Note that `@lgc.load.user.data` is generated after lowering of `@lgc.load.buffer.desc` (lgc-lower-desc pass).
// REVERSETEST-DAG: %{{[0-9]+}} = call i32 @lgc.load.user.data__i32(i32 0)
// REVERSETEST-DAG: %{{[0-9]+}} = call ptr addrspace(4) @lgc.special.user.data.Workgroup(i32 268435462)
// REVERSETEST-DAG: %{{[0-9]+}} = call i32 @lgc.load.user.data__i32(i32 4)
// There should be a select between the reversed thread group ID and original thread group ID
// REVERSETEST: %{{[0-9]+}} = select i1 %{{[0-9]+}}, <3 x i32> %{{[0-9]+}}, <3 x i32> %{{[0-9]+}}
// REVERSETEST: AMDLLPC SUCCESS
// END_REVERSETEST
// BEGIN_NOTREVERSETEST
// RUN: amdllpc -v %gfxip %s --reverse-thread-group=0 | FileCheck -check-prefix=NOTREVERSETEST %s
// NOTREVERSETEST-LABEL: {{^// LLPC}} LGC before-lowering results
// There should not be a call to get the gl_NumWorkGroups
// NOTREVERSETEST-NOT: %{{[0-9]+}} = call ptr addrspace(4) @lgc.special.user.data.Workgroup(i32 268435462)
// There should not be a call to get the internal buffer descriptor
// NOTREVERSETEST-NOT: %{{[0-9]+}} = call ptr addrspace(4) @lgc.descriptor.table.addr(i32 10, i32 10, i64 4294967295, i32 7, i32 -1)
// There should not be a select between the reversed thread group ID and original thread group ID
// NOTREVERSETEST-NOT: %{{[0-9]+}} = select i1 %{{[0-9]+}}, <3 x i32> %{{[0-9]+}}, <3 x i32> %{{[0-9]+}}
// NOTREVERSETEST: AMDLLPC SUCCESS
// END_NOTREVERSETEST
