// BEGIN_SHADERTEST
/*
; Check that a hit attribute value that is not reported is never written out.
; RUN: amdllpc -filetype=asm %gfxip -o - %s | FileCheck -check-prefix=CHECK %s
; CHECK: 0x12345678
; CHECK-NOT: 0x87654321
*/
// END_SHADERTEST

#version 460
#extension GL_EXT_ray_tracing : require
hitAttributeEXT int attr;
void main()
{
  attr = 0x12345678;
  reportIntersectionEXT(1.0f, 0);
  attr = 0x87654321;
}
