/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

struct Buf
{
    int8_t  i8;
    i8vec2  i8v2;
    i8vec3  i8v3;
    i8vec4  i8v4;

} bufIn;

shared Buf buf[4];

layout(binding = 0) buffer BufOut
{
    i8vec4 i8v4;

} bufOut;

void main()
{
    uint i = gl_GlobalInvocationID.x % 4;

    switch (i)
    {
    case 0:
        bufOut.i8v4.x = buf[i].i8++;
        break;
    case 1:
        bufOut.i8v4.xy = buf[i].i8v2++;
        break;
    case 2:
        bufOut.i8v4.xyz = buf[i].i8v3++;
        break;
    case 3:
        bufOut.i8v4 = buf[i].i8v4++;
        break;
    }
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -enable-load-scalarizer=false -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}} FE lowering results
; SHADERTEST-COUNT-4: getelementptr {{.*}}[4 x { i8, <2 x i8>, <3 x i8>, <4 x i8> }], ptr addrspace(3) @{{.*}}, i32 0, i32 {{%?[0-9]+}}, i32 {{[0-3]}}
; SHADERTEST-LABEL: {{^// LLPC}} LGC lowering results
; SHADERTEST: load i8, ptr addrspace(3) @{{.*}}, align {{1|4}}
; SHADERTEST: store i8 %{{[0-9]*}}, ptr addrspace(3) @{{.*}}, align {{1|4}}
; SHADERTEST-COUNT-3: load <{{[2-4]}} x i8>, ptr addrspace(3) getelementptr inbounds {{(nuw )?}}(i8, ptr addrspace(3) @{{.*}}, i32 {{14|28|44}}), align {{[2|4]}}
; SHADERTEST-COUNT-3: store <{{[2-4]}} x i8> %{{[0-9]*}}, ptr addrspace(3) getelementptr inbounds {{(nuw )?}}(i8, ptr addrspace(3) @{{.*}}, i32 {{14|28|44}}), align {{[2|4]}}
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
