/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core
#extension GL_AMD_gpu_shader_int16 : enable

layout(set = 0, binding = 0) uniform UBO {
    int16_t m1;
    int16_t m2;
    uint16_t m3;
    uint16_t m4;
    i16vec4 m5;
    i16vec4 m6;
    u16vec4 m7;
    u16vec4 m8;
};

layout(set = 1, binding = 0) buffer SSBO {
    int16_t mOut1;
    uint16_t mOut2;
    uint16_t mOut3;
    i16vec4 mOut4;
    u16vec4 mOut5;
    u16vec4 mOut6;
};

void main()
{
    int16_t  a = m1 & m2;
    uint16_t b = m2 & m3;
    uint16_t c = m3 & m4;

    i16vec4 va = m5 & m6;
    u16vec4 vb = m6 & m7;
    u16vec4 vc = m7 & m8;

    int16_t  d = m1 ^ a;
    uint16_t e = m2 ^ b;
    uint16_t f = m3 ^ c;

    i16vec4 vd = m5 ^ va;
    u16vec4 ve = m6 ^ vb;
    u16vec4 vf = m7 ^ vc;

    int16_t  g = m1 | d;
    uint16_t h = m2 | e;
    uint16_t i = m3 | f;

    i16vec4 vg = m5 | vd;
    u16vec4 vh = m6 | ve;
    u16vec4 vi = m7 | vf;

    u16vec4 vj = ~vi;

    mOut1 = g;
    mOut2 = h;
    mOut3 = i;
    mOut4 = vg;
    mOut5 = vh;
    mOut6 = vj;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
