/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

#version 450 core

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

layout(binding = 0) uniform BufIn
{
    int8_t  i8;
    uint8_t u8;

    i8vec2  i8v2;
    u8vec2  u8v2;

    i8vec3  i8v3;
    u8vec3  u8v3;

    i8vec4  i8v4;
    u8vec4  u8v4;

} bufIn;

layout(binding = 1) buffer BufOut
{
    int8_t  i8;
    uint8_t u8;

    i8vec2  i8v2;
    u8vec2  u8v2;

    i8vec3  i8v3;
    u8vec3  u8v3;

    i8vec4  i8v4;
    u8vec4  u8v4;

} bufOut;

void main()
{
    bufOut.i8   = bufIn.i8;
    bufOut.i8v2 = bufIn.i8v2;
    bufOut.i8v3 = bufIn.i8v3;
    bufOut.i8v4 = bufIn.i8v4;
}
// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
