include $(ICD_DEPTH)/make/icddefs

include $(ICD_DEPTH)/make/Makefile.$(ICD_PLATFORM).icd

LCXXINCS += -I$(ICD_DEPTH)/api/include/khronos
LCXXINCS += -I$(ICD_DEPTH)/api/compiler/llpc/imported/spirv
LCXXINCS += -I$(ICD_DEPTH)/api/compiler/llpc/include
LCXXINCS += -I$(ICD_DEPTH)/api/compiler/llpc/tool/vfx

vpath %.cpp $(ICD_DEPTH)/api/compiler/llpc/tool/vfx

CPPFILES +=              \
    vfxParser.cpp        \
    vfxPipelineDoc.cpp   \
    vfxRenderDoc.cpp     \
    vfxSection.cpp       \
    vfxEnumsConverter.cpp

LIB_TARGET = icdapicompilerllpctoolvfx

ifeq ($(ICD_PLATFORM), win)
    LCXXDEFS += -D_SCL_SECURE_NO_WARNINGS       \
                -DUNICODE                       \
                -D_UNICODE
endif

#if VKI_BUILD_GFX10
ifeq ($(VKI_BUILD_GFX10),1)
    LCXXDEFS += -DVKI_BUILD_GFX10=1
    LCXXDEFS += -DLLPC_BUILD_GFX10=1
endif
#endif

ifeq ($(ICD_PLATFORM), win)
    LCXXOPTS += /wd4267 \
                /wd4312
endif

ifneq ($(ICD_PLATFORM), win)
    # Non-windows: gcc-style options.
    # disable link time optimization in VFX to fix build failure of standalone compiler.
    LCXXOPTS := $(filter-out -flto,$(LCXXOPTS))
    LCXXOPTS := $(filter-out -fuse-linker-plugin,$(LCXXOPTS))
    LCXXOPTS := $(filter-out -Wno-odr,$(LCXXOPTS))
    LCOPTS   := $(filter-out -flto,$(LCOPTS))
    LCOPTS   := $(filter-out -fuse-linker-plugin,$(LCOPTS))
    LCOPTS   := $(filter-out -Wno-odr,$(LCOPTS))
endif

# Replace calling convention /Gr (__fastcall) with /Gd (__cdecl) to link LLPC.
ifeq ($(ICD_PLATFORM), win)
    LCXXOPTS := $(filter-out /Gr, $(LCXXOPTS))
    LCXXOPTS += /Gd
endif

include $(ICD_DEPTH)/make/icdrules
