#version 450

#define SIZE 65536

layout(set = 0, binding = 0) buffer _ {
    int a[SIZE];
    int b[SIZE];
};

void main() {
    for (int i = 0; i < SIZE; i++) {
        a[i] = b[i];
    }
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST: call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(
; SHADERTEST: call void @llvm.amdgcn.raw.buffer.store.v4i32(<4 x i32> %{{[0-9]*}}
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
