#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int16: enable

#define SIZE 65536

layout(set = 0, binding = 0) buffer _ {
    int16_t a[SIZE];
    int16_t b[SIZE];
};

void main() {
    for (int i = 0; i < SIZE; i++) {
        a[i] = b[i];
    }
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST: call i16 @llvm.amdgcn.raw.buffer.load.i16(
; SHADERTEST: call void @llvm.amdgcn.buffer.store.short(
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
