#version 450
layout(set = 0, binding = 0) buffer BO
{
    vec4 m;
};

layout(local_size_x = 1) in;
void main()
{
    m.y = m.x;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s

; SHADERTEST-LABEL: {{^// LLPC}} SPIR-V lowering results
; SHADERTEST: %{{[^ ]+}} = call i8 addrspace(7)* {{.*}} @lgc.create.load.buffer.desc.{{[0-9a-z.]*}}(i32 0, i32 0, i32 0,
; SHADERTEST: %{{[^ ]+}} = load float, float addrspace(7)* %{{[^, ]+}}, align 4
; SHADERTEST: %{{[^ ]+}} = getelementptr inbounds i8, i8 addrspace(7)* %{{[^, ]+}}, i64 4
; SHADERTEST: store float %{{[^, ]+}}, float addrspace(7)* %{{[^, ]+}}, align 4

; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
