; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt --verify-each -passes='dxil-cont-lgc-rt-op-converter,lint,lower-raytracing-pipeline,lint,remove-types-metadata' -S %s --lint-abort-on-error | FileCheck -check-prefix=LOWERRAYTRACINGPIPELINE %s

; Test that we correctly save and restore registers before/after recursive
; TraceRay or CallShader if there are live values in payload registers that
; are not overwritten at the end of the shader, e.g. the payload memory pointer.
; This applies to ClosestHit and Miss.
; This file was generated by compiling payload_save_registers.ll.hlsl
; and manually adding some gpurt content at the end.
; Also, function name mangling was removed.
; Note that the payload has payload access qualifiers set.

target datalayout = "e-m:e-p:64:32-p20:32:32-p21:32:32-p32:32:32-i1:32-i8:8-i16:16-i32:32-i64:32-f16:16-f32:32-f64:32-v8:8-v16:16-v32:32-v48:32-v64:32-v80:32-v96:32-v112:32-v128:32-v144:32-v160:32-v176:32-v192:32-v208:32-v224:32-v240:32-v256:32-n8:16:32"

%dx.types.Handle = type { i8* }
%struct.OuterPayload = type { [15 x float], [15 x float] }
%struct.InnerPayload = type { float }
%dx.types.ResourceProperties = type { i32, i32 }
%struct.DispatchSystemData = type { i32 }
%struct.TraversalData = type { %struct.SystemData }
%struct.SystemData = type { %struct.DispatchSystemData }
%struct.AnyHitTraversalData = type { %struct.TraversalData, %struct.HitData }
%struct.HitData = type { float, i32 }
%struct.BuiltInTriangleIntersectionAttributes = type { <2 x float> }
%struct.RaytracingAccelerationStructure = type { i32 }

@"\01?myAccelerationStructure@@3URaytracingAccelerationStructure@@A" = external constant %dx.types.Handle, align 4

; Function Attrs: nounwind
define void @Miss(%struct.OuterPayload* noalias nocapture %outerPayload) #0 !types !23 {
; LOWERRAYTRACINGPIPELINE-LABEL: define %struct.DispatchSystemData @Miss(
; LOWERRAYTRACINGPIPELINE-SAME: i64 [[RETURNADDR:%.*]], [[STRUCT_SYSTEMDATA:%.*]] [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] !lgc.rt.shaderstage [[META25:![0-9]+]] !continuation.registercount [[META23:![0-9]+]] !continuation [[META26:![0-9]+]] {
; LOWERRAYTRACINGPIPELINE-NEXT:    [[SYSTEM_DATA_ALLOCA:%.*]] = alloca [[STRUCT_SYSTEMDATA]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP2:%.*]] = alloca [[STRUCT_OUTERPAYLOAD:%.*]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_SYSTEMDATA]] [[TMP0]], ptr [[SYSTEM_DATA_ALLOCA]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP3:%.*]] = getelementptr inbounds [[STRUCT_SYSTEMDATA]], ptr [[SYSTEM_DATA_ALLOCA]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP36:%.*]] = load ptr addrspace(32), ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP7]], ptr [[TMP4]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP9:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP9]], ptr [[TMP8]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP11]], ptr [[TMP10]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP13:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP13]], ptr [[TMP12]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP15:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP15]], ptr [[TMP14]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP17:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP17]], ptr [[TMP16]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP19:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP19]], ptr [[TMP18]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP21:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP21]], ptr [[TMP20]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP23:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP23]], ptr [[TMP22]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP25:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP25]], ptr [[TMP24]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP27:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP27]], ptr [[TMP26]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP29:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP29]], ptr [[TMP28]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP31:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP31]], ptr [[TMP30]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP32:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP33:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP33]], ptr [[TMP32]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP35:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP35]], ptr [[TMP34]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP37:%.*]] = load i32, ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP38:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP39:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP40:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP41:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP42:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP43:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP44:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP49:%.*]] = load i32, ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @amd.dx.setLocalRootIndex(i32 5)
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP45:%.*]] = load [[DX_TYPES_HANDLE:%.*]], ptr @"\01?myAccelerationStructure@@3URaytracingAccelerationStructure@@A", align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP46:%.*]] = alloca [[STRUCT_INNERPAYLOAD:%.*]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP47:%.*]] = bitcast ptr [[TMP46]] to ptr
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[TMP47]]) #[[ATTR0]]
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP48:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP51:%.*]] = load float, ptr [[TMP48]], align 4, !tbaa [[TBAA27:![0-9]+]]
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP50:%.*]] = getelementptr inbounds [[STRUCT_INNERPAYLOAD]], ptr [[TMP46]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP51]], ptr [[TMP50]], align 4, !tbaa [[TBAA27]]
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP55:%.*]] = call [[DX_TYPES_HANDLE]] [[DX_OP_CREATEHANDLEFORLIB_DX_TYPES_HANDLE:@[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]](i32 160, [[DX_TYPES_HANDLE]] [[TMP45]])
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP52:%.*]] = call [[DX_TYPES_HANDLE]] [[DX_OP_ANNOTATEHANDLE:@[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]](i32 216, [[DX_TYPES_HANDLE]] [[TMP55]], [[DX_TYPES_RESOURCEPROPERTIES:%.*]] { i32 16, i32 0 })
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP53:%.*]] = call i64 @amd.dx.getAccelStructAddr([[DX_TYPES_HANDLE]] [[TMP52]])
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP54:%.*]] = getelementptr inbounds [[STRUCT_SYSTEMDATA]], ptr [[SYSTEM_DATA_ALLOCA]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[DIS_DATA_I:%.*]] = load [[STRUCT_DISPATCHSYSTEMDATA:%.*]], ptr [[TMP54]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[SYS_DATA_I:%.*]] = insertvalue [[STRUCT_SYSTEMDATA]] undef, [[STRUCT_DISPATCHSYSTEMDATA]] [[DIS_DATA_I]], 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TRAV_DATA_I:%.*]] = insertvalue [[STRUCT_TRAVERSALDATA:%.*]] undef, [[STRUCT_SYSTEMDATA]] [[SYS_DATA_I]], 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP57:%.*]] = getelementptr inbounds [[STRUCT_INNERPAYLOAD]], ptr [[TMP46]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP61:%.*]] = load i32, ptr [[TMP57]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP61]], ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP56:%.*]] = call ptr inttoptr (i64 4 to ptr)([[STRUCT_TRAVERSALDATA]] [[TRAV_DATA_I]], i64 poison), !continuation.registercount [[META31:![0-9]+]], !continuation.returnedRegistercount [[META31]]
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP58:%.*]] = call [[STRUCT_DISPATCHSYSTEMDATA]] [[AWAIT:@[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]](ptr [[TMP56]])
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_INNERPAYLOAD]] poison, ptr [[TMP46]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP59:%.*]] = getelementptr inbounds [[STRUCT_INNERPAYLOAD]], ptr [[TMP46]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP97:%.*]] = load i32, ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP97]], ptr [[TMP59]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_DISPATCHSYSTEMDATA]] [[TMP58]], ptr [[TMP54]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @amd.dx.setLocalRootIndex(i32 5)
; LOWERRAYTRACINGPIPELINE-NEXT:    br label [[DOTSPLIT:%.*]]
; LOWERRAYTRACINGPIPELINE:       .split:
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP60:%.*]] = load float, ptr [[TMP50]], align 4, !tbaa [[TBAA27]]
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP60]], ptr [[TMP48]], align 4, !tbaa [[TBAA27]]
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[TMP47]]) #[[ATTR0]]
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP37]], ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP38]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP39]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP40]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP41]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP42]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP43]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP44]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP49]], ptr addrspace(20) getelementptr (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP67:%.*]] = load ptr addrspace(32), ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP62:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP71:%.*]] = load i32, ptr [[TMP62]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP71]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP64:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP73:%.*]] = load i32, ptr [[TMP64]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP73]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP66:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP75:%.*]] = load i32, ptr [[TMP66]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP75]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP68:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP77:%.*]] = load i32, ptr [[TMP68]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP77]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP70:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP79:%.*]] = load i32, ptr [[TMP70]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP79]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP72:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP81:%.*]] = load i32, ptr [[TMP72]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP81]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP74:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP83:%.*]] = load i32, ptr [[TMP74]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP83]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP76:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP85:%.*]] = load i32, ptr [[TMP76]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP85]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP78:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP87:%.*]] = load i32, ptr [[TMP78]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP87]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP80:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP89:%.*]] = load i32, ptr [[TMP80]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP89]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP82:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP91:%.*]] = load i32, ptr [[TMP82]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP91]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP84:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP93:%.*]] = load i32, ptr [[TMP84]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP93]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP86:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP98:%.*]] = load i32, ptr [[TMP86]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP98]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP88:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP100:%.*]] = load i32, ptr [[TMP88]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP100]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP90:%.*]] = getelementptr inbounds i32, ptr [[TMP62]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP101:%.*]] = load i32, ptr [[TMP90]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP101]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP94:%.*]] = getelementptr inbounds [[STRUCT_SYSTEMDATA]], ptr [[SYSTEM_DATA_ALLOCA]], i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP95:%.*]] = load [[STRUCT_DISPATCHSYSTEMDATA]], ptr [[TMP94]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void (...) @lgc.ilcps.return(i64 [[RETURNADDR]], [[STRUCT_DISPATCHSYSTEMDATA]] [[TMP95]]), !continuation.registercount [[META23]]
; LOWERRAYTRACINGPIPELINE-NEXT:    unreachable
;
  %1 = load %dx.types.Handle, %dx.types.Handle* @"\01?myAccelerationStructure@@3URaytracingAccelerationStructure@@A", align 4
  %2 = alloca %struct.InnerPayload, align 4
  %3 = bitcast %struct.InnerPayload* %2 to i8*
  call void @llvm.lifetime.start.p0i8(i64 4, i8* %3) #0
  %4 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 14
  %5 = load float, float* %4, align 4, !tbaa !25
  %6 = getelementptr inbounds %struct.InnerPayload, %struct.InnerPayload* %2, i32 0, i32 0
  store float %5, float* %6, align 4, !tbaa !25
  %7 = call %dx.types.Handle @dx.op.createHandleForLib.dx.types.Handle(i32 160, %dx.types.Handle %1)
  %8 = call %dx.types.Handle @dx.op.annotateHandle(i32 216, %dx.types.Handle %7, %dx.types.ResourceProperties { i32 16, i32 0 })
  call void @dx.op.traceRay.struct.InnerPayload(i32 157, %dx.types.Handle %8, i32 0, i32 0, i32 0, i32 0, i32 0, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 0.000000e+00, float 1.000000e+00, %struct.InnerPayload* nonnull %2)
  %9 = load float, float* %6, align 4, !tbaa !25
  store float %9, float* %4, align 4, !tbaa !25
  call void @llvm.lifetime.end.p0i8(i64 4, i8* %3) #0
  ret void
}

; Function Attrs: nounwind
define void @Callable(%struct.OuterPayload* noalias %outerPayload) #0 !types !23 {
; LOWERRAYTRACINGPIPELINE-LABEL: define %struct.DispatchSystemData @Callable(
; LOWERRAYTRACINGPIPELINE-SAME: i64 [[RETURNADDR:%.*]], [[STRUCT_DISPATCHSYSTEMDATA:%.*]] [[TMP0:%.*]]) #[[ATTR0]] !lgc.rt.shaderstage [[META32:![0-9]+]] !continuation.registercount [[META23]] !continuation [[META33:![0-9]+]] {
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP2:%.*]] = alloca [[STRUCT_OUTERPAYLOAD:%.*]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[SYSTEM_DATA_ALLOCA:%.*]] = alloca [[STRUCT_DISPATCHSYSTEMDATA]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP3:%.*]] = alloca [[STRUCT_OUTERPAYLOAD]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_DISPATCHSYSTEMDATA]] [[TMP0]], ptr [[SYSTEM_DATA_ALLOCA]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP7:%.*]] = load i32, ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP7]], ptr [[TMP4]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP9:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 1), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP9]], ptr [[TMP6]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 2), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP11]], ptr [[TMP8]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP13:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 3), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP13]], ptr [[TMP10]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP15:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 4), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP15]], ptr [[TMP12]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP17:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 5), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP17]], ptr [[TMP14]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP19:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 6), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP19]], ptr [[TMP16]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP21:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP21]], ptr [[TMP18]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP23:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP23]], ptr [[TMP20]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP25:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP25]], ptr [[TMP22]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP27:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP27]], ptr [[TMP24]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP29:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP29]], ptr [[TMP26]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP31:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP31]], ptr [[TMP28]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP33:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP33]], ptr [[TMP30]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP32:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP35:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP35]], ptr [[TMP32]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 15
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP39:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP39]], ptr [[TMP34]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP36:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 16
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP41:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP41]], ptr [[TMP36]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP38:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 17
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP43:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP43]], ptr [[TMP38]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 18
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP45:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP45]], ptr [[TMP40]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP42:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 19
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP47:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP47]], ptr [[TMP42]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP44:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 20
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP49:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP49]], ptr [[TMP44]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP46:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 21
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP51:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP51]], ptr [[TMP46]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP48:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 22
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP53:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP53]], ptr [[TMP48]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP50:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 23
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP55:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP55]], ptr [[TMP50]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP52:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 24
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP57:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP57]], ptr [[TMP52]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP54:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 25
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP59:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP59]], ptr [[TMP54]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP56:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 26
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP61:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP61]], ptr [[TMP56]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP58:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 27
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP63:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP63]], ptr [[TMP58]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP60:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 28
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP65:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP65]], ptr [[TMP60]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP62:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i32 29
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP67:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP67]], ptr [[TMP62]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @amd.dx.setLocalRootIndex(i32 5)
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP68:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP69:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP70:%.*]] = load float, ptr [[TMP69]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP70]], ptr [[TMP68]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP71:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP72:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP73:%.*]] = load float, ptr [[TMP72]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP73]], ptr [[TMP71]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP74:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP75:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP76:%.*]] = load float, ptr [[TMP75]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP76]], ptr [[TMP74]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP77:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP78:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP79:%.*]] = load float, ptr [[TMP78]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP79]], ptr [[TMP77]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP80:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP81:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP82:%.*]] = load float, ptr [[TMP81]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP82]], ptr [[TMP80]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP83:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP84:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP85:%.*]] = load float, ptr [[TMP84]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP85]], ptr [[TMP83]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP86:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP87:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP88:%.*]] = load float, ptr [[TMP87]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP88]], ptr [[TMP86]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP89:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP90:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP91:%.*]] = load float, ptr [[TMP90]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP91]], ptr [[TMP89]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP92:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP93:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP94:%.*]] = load float, ptr [[TMP93]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP94]], ptr [[TMP92]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP95:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP96:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP97:%.*]] = load float, ptr [[TMP96]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP97]], ptr [[TMP95]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP98:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP99:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP100:%.*]] = load float, ptr [[TMP99]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP100]], ptr [[TMP98]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP101:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP102:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP103:%.*]] = load float, ptr [[TMP102]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP103]], ptr [[TMP101]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP104:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP105:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP106:%.*]] = load float, ptr [[TMP105]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP106]], ptr [[TMP104]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP107:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP108:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP109:%.*]] = load float, ptr [[TMP108]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP109]], ptr [[TMP107]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP110:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 0, i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP111:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 0, i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP112:%.*]] = load float, ptr [[TMP111]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP112]], ptr [[TMP110]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP113:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP114:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP115:%.*]] = load float, ptr [[TMP114]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP115]], ptr [[TMP113]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP116:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP117:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP118:%.*]] = load float, ptr [[TMP117]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP118]], ptr [[TMP116]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP119:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP120:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP121:%.*]] = load float, ptr [[TMP120]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP121]], ptr [[TMP119]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP122:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP123:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP124:%.*]] = load float, ptr [[TMP123]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP124]], ptr [[TMP122]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP125:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP126:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP127:%.*]] = load float, ptr [[TMP126]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP127]], ptr [[TMP125]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP128:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP129:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP130:%.*]] = load float, ptr [[TMP129]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP130]], ptr [[TMP128]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP131:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP132:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP133:%.*]] = load float, ptr [[TMP132]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP133]], ptr [[TMP131]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP134:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP135:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP136:%.*]] = load float, ptr [[TMP135]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP136]], ptr [[TMP134]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP137:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP138:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP139:%.*]] = load float, ptr [[TMP138]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP139]], ptr [[TMP137]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP140:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP141:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP142:%.*]] = load float, ptr [[TMP141]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP142]], ptr [[TMP140]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP143:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP144:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP145:%.*]] = load float, ptr [[TMP144]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP145]], ptr [[TMP143]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP146:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP147:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP148:%.*]] = load float, ptr [[TMP147]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP148]], ptr [[TMP146]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP149:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP150:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP151:%.*]] = load float, ptr [[TMP150]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP151]], ptr [[TMP149]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP152:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP153:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP154:%.*]] = load float, ptr [[TMP153]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP154]], ptr [[TMP152]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP155:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0, i32 1, i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP156:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0, i32 1, i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP157:%.*]] = load float, ptr [[TMP156]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP157]], ptr [[TMP155]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[DIS_DATA_I:%.*]] = load [[STRUCT_DISPATCHSYSTEMDATA]], ptr [[SYSTEM_DATA_ALLOCA]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP158:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP161:%.*]] = load i32, ptr [[TMP158]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP161]], ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP159:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP163:%.*]] = load i32, ptr [[TMP159]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP163]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 1), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP184:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP165:%.*]] = load i32, ptr [[TMP184]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP165]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 2), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP160:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP167:%.*]] = load i32, ptr [[TMP160]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP167]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 3), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP162:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP169:%.*]] = load i32, ptr [[TMP162]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP169]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 4), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP164:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP171:%.*]] = load i32, ptr [[TMP164]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP171]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 5), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP166:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP173:%.*]] = load i32, ptr [[TMP166]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP173]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 6), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP168:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP175:%.*]] = load i32, ptr [[TMP168]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP175]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP170:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP177:%.*]] = load i32, ptr [[TMP170]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP177]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP172:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP179:%.*]] = load i32, ptr [[TMP172]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP179]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP174:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP181:%.*]] = load i32, ptr [[TMP174]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP181]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP176:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP183:%.*]] = load i32, ptr [[TMP176]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP183]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP178:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP185:%.*]] = load i32, ptr [[TMP178]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP185]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP180:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP187:%.*]] = load i32, ptr [[TMP180]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP187]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP182:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP189:%.*]] = load i32, ptr [[TMP182]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP189]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP191:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 15
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP193:%.*]] = load i32, ptr [[TMP191]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP193]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP186:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 16
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP195:%.*]] = load i32, ptr [[TMP186]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP195]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP188:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 17
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP197:%.*]] = load i32, ptr [[TMP188]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP197]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP190:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 18
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP199:%.*]] = load i32, ptr [[TMP190]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP199]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP192:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 19
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP201:%.*]] = load i32, ptr [[TMP192]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP201]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP194:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 20
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP203:%.*]] = load i32, ptr [[TMP194]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP203]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP196:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 21
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP205:%.*]] = load i32, ptr [[TMP196]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP205]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP198:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 22
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP207:%.*]] = load i32, ptr [[TMP198]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP207]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP200:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 23
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP209:%.*]] = load i32, ptr [[TMP200]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP209]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP202:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 24
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP211:%.*]] = load i32, ptr [[TMP202]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP211]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP204:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 25
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP213:%.*]] = load i32, ptr [[TMP204]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP213]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP206:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 26
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP215:%.*]] = load i32, ptr [[TMP206]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP215]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP208:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 27
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP217:%.*]] = load i32, ptr [[TMP208]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP217]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP210:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 28
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP219:%.*]] = load i32, ptr [[TMP210]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP219]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP212:%.*]] = getelementptr inbounds i32, ptr [[TMP158]], i32 29
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP221:%.*]] = load i32, ptr [[TMP212]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP221]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP214:%.*]] = call ptr inttoptr (i64 2 to ptr)([[STRUCT_DISPATCHSYSTEMDATA]] [[DIS_DATA_I]]), !continuation.registercount [[META23]], !continuation.returnedRegistercount [[META23]]
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP223:%.*]] = call [[STRUCT_DISPATCHSYSTEMDATA]] [[AWAIT_1:@[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]](ptr [[TMP214]])
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_OUTERPAYLOAD]] poison, ptr [[TMP2]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP224:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP2]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP227:%.*]] = load i32, ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP227]], ptr [[TMP224]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP218:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP229:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 1), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP229]], ptr [[TMP218]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP220:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP231:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 2), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP231]], ptr [[TMP220]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP222:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP233:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 3), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP233]], ptr [[TMP222]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP225:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP235:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 4), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP235]], ptr [[TMP225]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP226:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP237:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 5), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP237]], ptr [[TMP226]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP228:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP239:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 6), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP239]], ptr [[TMP228]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP230:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP241:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP241]], ptr [[TMP230]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP232:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP243:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP243]], ptr [[TMP232]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP234:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP245:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP245]], ptr [[TMP234]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP236:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP247:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP247]], ptr [[TMP236]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP238:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP249:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP249]], ptr [[TMP238]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP240:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP251:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP251]], ptr [[TMP240]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP242:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP253:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP253]], ptr [[TMP242]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP244:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP255:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP255]], ptr [[TMP244]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP246:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 15
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP259:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP259]], ptr [[TMP246]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP248:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 16
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP261:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP261]], ptr [[TMP248]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP250:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 17
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP263:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP263]], ptr [[TMP250]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP252:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 18
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP265:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP265]], ptr [[TMP252]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP254:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 19
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP267:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP267]], ptr [[TMP254]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP256:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 20
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP269:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP269]], ptr [[TMP256]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP258:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 21
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP270:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP270]], ptr [[TMP258]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP260:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 22
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP272:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP272]], ptr [[TMP260]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP262:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 23
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP274:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP274]], ptr [[TMP262]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP264:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 24
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP276:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP276]], ptr [[TMP264]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP266:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 25
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP278:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP278]], ptr [[TMP266]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP268:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 26
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP280:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP280]], ptr [[TMP268]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP271:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 27
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP282:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP282]], ptr [[TMP271]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP273:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 28
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP284:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP284]], ptr [[TMP273]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP275:%.*]] = getelementptr inbounds i32, ptr [[TMP224]], i32 29
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP286:%.*]] = load i32, ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP286]], ptr [[TMP275]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store [[STRUCT_DISPATCHSYSTEMDATA]] [[TMP223]], ptr [[SYSTEM_DATA_ALLOCA]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void @amd.dx.setLocalRootIndex(i32 5)
; LOWERRAYTRACINGPIPELINE-NEXT:    br label [[DOTSPLIT:%.*]]
; LOWERRAYTRACINGPIPELINE:       .split:
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP288:%.*]] = load float, ptr [[TMP68]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP288]], ptr [[TMP69]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP277:%.*]] = load float, ptr [[TMP71]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP277]], ptr [[TMP72]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP290:%.*]] = load float, ptr [[TMP74]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP290]], ptr [[TMP75]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP279:%.*]] = load float, ptr [[TMP77]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP279]], ptr [[TMP78]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP292:%.*]] = load float, ptr [[TMP80]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP292]], ptr [[TMP81]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP281:%.*]] = load float, ptr [[TMP83]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP281]], ptr [[TMP84]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP294:%.*]] = load float, ptr [[TMP86]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP294]], ptr [[TMP87]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP283:%.*]] = load float, ptr [[TMP89]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP283]], ptr [[TMP90]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP296:%.*]] = load float, ptr [[TMP92]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP296]], ptr [[TMP93]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP285:%.*]] = load float, ptr [[TMP95]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP285]], ptr [[TMP96]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP298:%.*]] = load float, ptr [[TMP98]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP298]], ptr [[TMP99]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP287:%.*]] = load float, ptr [[TMP101]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP287]], ptr [[TMP102]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP300:%.*]] = load float, ptr [[TMP104]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP300]], ptr [[TMP105]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP289:%.*]] = load float, ptr [[TMP107]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP289]], ptr [[TMP108]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP302:%.*]] = load float, ptr [[TMP110]], align 8
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP302]], ptr [[TMP111]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP291:%.*]] = load float, ptr [[TMP113]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP291]], ptr [[TMP114]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP306:%.*]] = load float, ptr [[TMP116]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP306]], ptr [[TMP117]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP293:%.*]] = load float, ptr [[TMP119]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP293]], ptr [[TMP120]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP307:%.*]] = load float, ptr [[TMP122]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP307]], ptr [[TMP123]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP295:%.*]] = load float, ptr [[TMP125]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP295]], ptr [[TMP126]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP309:%.*]] = load float, ptr [[TMP128]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP309]], ptr [[TMP129]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP297:%.*]] = load float, ptr [[TMP131]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP297]], ptr [[TMP132]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP311:%.*]] = load float, ptr [[TMP134]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP311]], ptr [[TMP135]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP299:%.*]] = load float, ptr [[TMP137]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP299]], ptr [[TMP138]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP313:%.*]] = load float, ptr [[TMP140]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP313]], ptr [[TMP141]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP301:%.*]] = load float, ptr [[TMP143]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP301]], ptr [[TMP144]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP315:%.*]] = load float, ptr [[TMP146]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP315]], ptr [[TMP147]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP303:%.*]] = load float, ptr [[TMP149]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP303]], ptr [[TMP150]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP304:%.*]] = load float, ptr [[TMP152]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP304]], ptr [[TMP153]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP305:%.*]] = load float, ptr [[TMP155]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store float [[TMP305]], ptr [[TMP156]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP318:%.*]] = getelementptr inbounds [[STRUCT_OUTERPAYLOAD]], ptr [[TMP3]], i32 0
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP321:%.*]] = load i32, ptr [[TMP318]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP321]], ptr addrspace(20) @PAYLOAD, align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP308:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 1
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP323:%.*]] = load i32, ptr [[TMP308]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP323]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 1), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP310:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 2
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP325:%.*]] = load i32, ptr [[TMP310]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP325]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 2), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP312:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 3
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP327:%.*]] = load i32, ptr [[TMP312]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP327]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 3), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP314:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP329:%.*]] = load i32, ptr [[TMP314]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP329]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 4), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP316:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 5
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP331:%.*]] = load i32, ptr [[TMP316]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP331]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 5), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP319:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 6
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP333:%.*]] = load i32, ptr [[TMP319]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP333]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 6), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP320:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 7
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP335:%.*]] = load i32, ptr [[TMP320]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP335]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 7), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP322:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 8
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP337:%.*]] = load i32, ptr [[TMP322]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP337]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 8), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP324:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 9
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP339:%.*]] = load i32, ptr [[TMP324]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP339]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 9), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP326:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 10
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP341:%.*]] = load i32, ptr [[TMP326]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP341]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 10), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP328:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 11
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP343:%.*]] = load i32, ptr [[TMP328]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP343]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 11), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP330:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 12
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP345:%.*]] = load i32, ptr [[TMP330]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP345]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 12), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP332:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 13
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP347:%.*]] = load i32, ptr [[TMP332]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP347]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 13), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP334:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 14
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP349:%.*]] = load i32, ptr [[TMP334]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP349]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 14), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP336:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 15
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP353:%.*]] = load i32, ptr [[TMP336]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP353]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 15), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP338:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 16
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP355:%.*]] = load i32, ptr [[TMP338]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP355]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 16), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP340:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 17
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP357:%.*]] = load i32, ptr [[TMP340]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP357]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 17), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP342:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 18
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP359:%.*]] = load i32, ptr [[TMP342]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP359]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 18), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP344:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 19
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP361:%.*]] = load i32, ptr [[TMP344]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP361]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 19), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP346:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 20
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP363:%.*]] = load i32, ptr [[TMP346]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP363]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 20), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP348:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 21
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP365:%.*]] = load i32, ptr [[TMP348]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP365]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 21), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP350:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 22
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP367:%.*]] = load i32, ptr [[TMP350]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP367]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 22), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP352:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 23
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP369:%.*]] = load i32, ptr [[TMP352]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP369]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 23), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP354:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 24
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP371:%.*]] = load i32, ptr [[TMP354]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP371]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 24), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP356:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 25
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP373:%.*]] = load i32, ptr [[TMP356]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP373]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 25), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP358:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 26
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP375:%.*]] = load i32, ptr [[TMP358]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP375]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 26), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP360:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 27
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP377:%.*]] = load i32, ptr [[TMP360]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP377]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 27), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP362:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 28
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP379:%.*]] = load i32, ptr [[TMP362]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP379]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 28), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP364:%.*]] = getelementptr inbounds i32, ptr [[TMP318]], i32 29
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP381:%.*]] = load i32, ptr [[TMP364]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    store i32 [[TMP381]], ptr addrspace(20) getelementptr inbounds (i32, ptr addrspace(20) @PAYLOAD, i32 29), align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    [[TMP382:%.*]] = load [[STRUCT_DISPATCHSYSTEMDATA]], ptr [[SYSTEM_DATA_ALLOCA]], align 4
; LOWERRAYTRACINGPIPELINE-NEXT:    call void (...) @lgc.ilcps.return(i64 [[RETURNADDR]], [[STRUCT_DISPATCHSYSTEMDATA]] [[TMP382]]), !continuation.registercount [[META23]]
; LOWERRAYTRACINGPIPELINE-NEXT:    unreachable
;
  %1 = alloca %struct.OuterPayload, align 8
  %2 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 0
  %3 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 0
  %4 = load float, float* %3, align 4
  store float %4, float* %2, align 8
  %5 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 1
  %6 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 1
  %7 = load float, float* %6, align 4
  store float %7, float* %5, align 4
  %8 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 2
  %9 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 2
  %10 = load float, float* %9, align 4
  store float %10, float* %8, align 8
  %11 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 3
  %12 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 3
  %13 = load float, float* %12, align 4
  store float %13, float* %11, align 4
  %14 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 4
  %15 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 4
  %16 = load float, float* %15, align 4
  store float %16, float* %14, align 8
  %17 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 5
  %18 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 5
  %19 = load float, float* %18, align 4
  store float %19, float* %17, align 4
  %20 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 6
  %21 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 6
  %22 = load float, float* %21, align 4
  store float %22, float* %20, align 8
  %23 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 7
  %24 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 7
  %25 = load float, float* %24, align 4
  store float %25, float* %23, align 4
  %26 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 8
  %27 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 8
  %28 = load float, float* %27, align 4
  store float %28, float* %26, align 8
  %29 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 9
  %30 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 9
  %31 = load float, float* %30, align 4
  store float %31, float* %29, align 4
  %32 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 10
  %33 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 10
  %34 = load float, float* %33, align 4
  store float %34, float* %32, align 8
  %35 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 11
  %36 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 11
  %37 = load float, float* %36, align 4
  store float %37, float* %35, align 4
  %38 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 12
  %39 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 12
  %40 = load float, float* %39, align 4
  store float %40, float* %38, align 8
  %41 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 13
  %42 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 13
  %43 = load float, float* %42, align 4
  store float %43, float* %41, align 4
  %44 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 0, i32 14
  %45 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 0, i32 14
  %46 = load float, float* %45, align 4
  store float %46, float* %44, align 8
  %47 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 0
  %48 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 0
  %49 = load float, float* %48, align 4
  store float %49, float* %47, align 4
  %50 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 1
  %51 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 1
  %52 = load float, float* %51, align 4
  store float %52, float* %50, align 4
  %53 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 2
  %54 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 2
  %55 = load float, float* %54, align 4
  store float %55, float* %53, align 4
  %56 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 3
  %57 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 3
  %58 = load float, float* %57, align 4
  store float %58, float* %56, align 4
  %59 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 4
  %60 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 4
  %61 = load float, float* %60, align 4
  store float %61, float* %59, align 4
  %62 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 5
  %63 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 5
  %64 = load float, float* %63, align 4
  store float %64, float* %62, align 4
  %65 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 6
  %66 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 6
  %67 = load float, float* %66, align 4
  store float %67, float* %65, align 4
  %68 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 7
  %69 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 7
  %70 = load float, float* %69, align 4
  store float %70, float* %68, align 4
  %71 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 8
  %72 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 8
  %73 = load float, float* %72, align 4
  store float %73, float* %71, align 4
  %74 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 9
  %75 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 9
  %76 = load float, float* %75, align 4
  store float %76, float* %74, align 4
  %77 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 10
  %78 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 10
  %79 = load float, float* %78, align 4
  store float %79, float* %77, align 4
  %80 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 11
  %81 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 11
  %82 = load float, float* %81, align 4
  store float %82, float* %80, align 4
  %83 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 12
  %84 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 12
  %85 = load float, float* %84, align 4
  store float %85, float* %83, align 4
  %86 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 13
  %87 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 13
  %88 = load float, float* %87, align 4
  store float %88, float* %86, align 4
  %89 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %1, i32 0, i32 1, i32 14
  %90 = getelementptr inbounds %struct.OuterPayload, %struct.OuterPayload* %outerPayload, i32 0, i32 1, i32 14
  %91 = load float, float* %90, align 4
  store float %91, float* %89, align 4
  call void @dx.op.callShader.struct.OuterPayload(i32 159, i32 0, %struct.OuterPayload* nonnull %1)
  %92 = load float, float* %2, align 8
  store float %92, float* %3, align 4
  %93 = load float, float* %5, align 4
  store float %93, float* %6, align 4
  %94 = load float, float* %8, align 8
  store float %94, float* %9, align 4
  %95 = load float, float* %11, align 4
  store float %95, float* %12, align 4
  %96 = load float, float* %14, align 8
  store float %96, float* %15, align 4
  %97 = load float, float* %17, align 4
  store float %97, float* %18, align 4
  %98 = load float, float* %20, align 8
  store float %98, float* %21, align 4
  %99 = load float, float* %23, align 4
  store float %99, float* %24, align 4
  %100 = load float, float* %26, align 8
  store float %100, float* %27, align 4
  %101 = load float, float* %29, align 4
  store float %101, float* %30, align 4
  %102 = load float, float* %32, align 8
  store float %102, float* %33, align 4
  %103 = load float, float* %35, align 4
  store float %103, float* %36, align 4
  %104 = load float, float* %38, align 8
  store float %104, float* %39, align 4
  %105 = load float, float* %41, align 4
  store float %105, float* %42, align 4
  %106 = load float, float* %44, align 8
  store float %106, float* %45, align 4
  %107 = load float, float* %47, align 4
  store float %107, float* %48, align 4
  %108 = load float, float* %50, align 4
  store float %108, float* %51, align 4
  %109 = load float, float* %53, align 4
  store float %109, float* %54, align 4
  %110 = load float, float* %56, align 4
  store float %110, float* %57, align 4
  %111 = load float, float* %59, align 4
  store float %111, float* %60, align 4
  %112 = load float, float* %62, align 4
  store float %112, float* %63, align 4
  %113 = load float, float* %65, align 4
  store float %113, float* %66, align 4
  %114 = load float, float* %68, align 4
  store float %114, float* %69, align 4
  %115 = load float, float* %71, align 4
  store float %115, float* %72, align 4
  %116 = load float, float* %74, align 4
  store float %116, float* %75, align 4
  %117 = load float, float* %77, align 4
  store float %117, float* %78, align 4
  %118 = load float, float* %80, align 4
  store float %118, float* %81, align 4
  %119 = load float, float* %83, align 4
  store float %119, float* %84, align 4
  %120 = load float, float* %86, align 4
  store float %120, float* %87, align 4
  %121 = load float, float* %89, align 4
  store float %121, float* %90, align 4
  ret void
}

; Function Attrs: nounwind
declare !types !29 void @dx.op.traceRay.struct.InnerPayload(i32, %dx.types.Handle, i32, i32, i32, i32, i32, float, float, float, float, float, float, float, float, %struct.InnerPayload*) #0

; Function Attrs: nounwind
declare !types !31 void @dx.op.callShader.struct.OuterPayload(i32, i32, %struct.OuterPayload*) #0

; Function Attrs: nounwind memory(none)
declare %dx.types.Handle @dx.op.annotateHandle(i32, %dx.types.Handle, %dx.types.ResourceProperties) #1

; Function Attrs: nounwind memory(read)
declare %dx.types.Handle @dx.op.createHandleForLib.dx.types.Handle(i32, %dx.types.Handle) #2

; Function Attrs: alwaysinline
declare %struct.DispatchSystemData @_cont_SetupRayGen() #3

; Function Attrs: alwaysinline
declare %struct.DispatchSystemData @_AmdAwaitTraversal(i64, %struct.TraversalData) #3

; Function Attrs: alwaysinline
declare %struct.DispatchSystemData @_AmdAwaitShader(i64, %struct.DispatchSystemData) #3

; Function Attrs: alwaysinline
declare %struct.AnyHitTraversalData @_AmdAwaitAnyHit(i64, %struct.AnyHitTraversalData, float, i32) #3

; Function Attrs: alwaysinline
declare !types !32 %struct.BuiltInTriangleIntersectionAttributes @_cont_GetTriangleHitAttributes(%struct.SystemData*) #3

; Function Attrs: alwaysinline
declare !types !34 void @_cont_SetTriangleHitAttributes(%struct.SystemData*, %struct.BuiltInTriangleIntersectionAttributes) #3

; Function Attrs: alwaysinline
declare !types !35 i1 @_cont_IsEndSearch(%struct.TraversalData*) #3

; Function Attrs: nounwind memory(read)
declare !types !37 i32 @_cont_HitKind(%struct.SystemData* nocapture readnone, %struct.HitData*) #2

; Function Attrs: nounwind memory(none)
declare !types !39 void @_AmdRestoreSystemData(%struct.DispatchSystemData*) #1

; Function Attrs: nounwind memory(none)
declare !types !41 void @_AmdRestoreSystemDataAnyHit(%struct.AnyHitTraversalData*) #1

; Function Attrs: alwaysinline
define i32 @_cont_GetLocalRootIndex(%struct.DispatchSystemData* %data) #3 !types !43 {
; LOWERRAYTRACINGPIPELINE-LABEL: define i32 @_cont_GetLocalRootIndex(
; LOWERRAYTRACINGPIPELINE-SAME: ptr [[DATA:%.*]]) #[[ATTR3:[0-9]+]] {
; LOWERRAYTRACINGPIPELINE-NEXT:    ret i32 5
;
  ret i32 5
}

; Function Attrs: alwaysinline
define void @_cont_TraceRay(%struct.DispatchSystemData* %data, i64 %0, i32 %1, i32 %2, i32 %3, i32 %4, i32 %5, float %6, float %7, float %8, float %9, float %10, float %11, float %12, float %13) #3 !types !44 {
  %dis_data = load %struct.DispatchSystemData, %struct.DispatchSystemData* %data, align 4
  %sys_data = insertvalue %struct.SystemData undef, %struct.DispatchSystemData %dis_data, 0
  %trav_data = insertvalue %struct.TraversalData undef, %struct.SystemData %sys_data, 0
  %newdata = call %struct.DispatchSystemData @_AmdAwaitTraversal(i64 4, %struct.TraversalData %trav_data)
  store %struct.DispatchSystemData %newdata, %struct.DispatchSystemData* %data, align 4
  call void @_AmdRestoreSystemData(%struct.DispatchSystemData* %data)
  ret void
}

; Function Attrs: alwaysinline
define void @_cont_CallShader(%struct.DispatchSystemData* %data, i32 %0) #3 !types !45 {
  %dis_data = load %struct.DispatchSystemData, %struct.DispatchSystemData* %data, align 4
  %newdata = call %struct.DispatchSystemData @_AmdAwaitShader(i64 2, %struct.DispatchSystemData %dis_data)
  store %struct.DispatchSystemData %newdata, %struct.DispatchSystemData* %data, align 4
  call void @_AmdRestoreSystemData(%struct.DispatchSystemData* %data)
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare !types !46 void @llvm.lifetime.start.p0i8(i64 immarg, i8* nocapture) #4

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare !types !46 void @llvm.lifetime.end.p0i8(i64 immarg, i8* nocapture) #4

attributes #0 = { nounwind }
attributes #1 = { nounwind memory(none) }
attributes #2 = { nounwind memory(read) }
attributes #3 = { alwaysinline }
attributes #4 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }

!llvm.ident = !{!0}
!dx.version = !{!1}
!dx.valver = !{!1}
!dx.shaderModel = !{!2}
!dx.resources = !{!3}
!dx.typeAnnotations = !{!7}
!dx.dxrPayloadAnnotations = !{!12}
!dx.entryPoints = !{!17, !18, !21}

!0 = !{!"dxcoob 2019.05.00"}
!1 = !{i32 1, i32 7}
!2 = !{!"lib", i32 6, i32 7}
!3 = !{!4, null, null, null}
!4 = !{!5}
!5 = !{i32 0, %struct.RaytracingAccelerationStructure* bitcast (%dx.types.Handle* @"\01?myAccelerationStructure@@3URaytracingAccelerationStructure@@A" to %struct.RaytracingAccelerationStructure*), !"myAccelerationStructure", i32 0, i32 3, i32 1, i32 16, i32 0, !6}
!6 = !{i32 0, i32 4}
!7 = !{i32 1, void (%struct.OuterPayload*)* @Miss, !8, void (%struct.OuterPayload*)* @Callable, !8}
!8 = !{!9, !11}
!9 = !{i32 1, !10, !10}
!10 = !{}
!11 = !{i32 2, !10, !10}
!12 = !{i32 0, %struct.OuterPayload undef, !13, %struct.InnerPayload undef, !16}
!13 = !{!14, !15}
!14 = !{i32 0, i32 771}
!15 = !{i32 0, i32 3}
!16 = !{!15}
!17 = !{null, !"", null, !3, null}
!18 = !{void (%struct.OuterPayload*)* @Miss, !"Miss", null, null, !19}
!19 = !{i32 8, i32 11, i32 6, i32 120, i32 5, !20}
!20 = !{i32 0}
!21 = !{void (%struct.OuterPayload*)* @Callable, !"Callable", null, null, !22}
!22 = !{i32 8, i32 12, i32 6, i32 120, i32 5, !20}
!23 = !{!"function", !"void", !24}
!24 = !{i32 0, %struct.OuterPayload poison}
!25 = !{!26, !26, i64 0}
!26 = !{!"float", !27, i64 0}
!27 = !{!"omnipotent char", !28, i64 0}
!28 = !{!"Simple C/C++ TBAA"}
!29 = !{!"function", !"void", i32 poison, %dx.types.Handle poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, float poison, float poison, float poison, float poison, float poison, float poison, float poison, float poison, !30}
!30 = !{i32 0, %struct.InnerPayload poison}
!31 = !{!"function", !"void", i32 poison, i32 poison, !24}
!32 = !{!"function", %struct.BuiltInTriangleIntersectionAttributes poison, !33}
!33 = !{i32 0, %struct.SystemData poison}
!34 = !{!"function", !"void", !33, %struct.BuiltInTriangleIntersectionAttributes poison}
!35 = !{!"function", i1 poison, !36}
!36 = !{i32 0, %struct.TraversalData poison}
!37 = !{!"function", i32 poison, !33, !38}
!38 = !{i32 0, %struct.HitData poison}
!39 = !{!"function", !"void", !40}
!40 = !{i32 0, %struct.DispatchSystemData poison}
!41 = !{!"function", !"void", !42}
!42 = !{i32 0, %struct.AnyHitTraversalData poison}
!43 = !{!"function", i32 poison, !40}
!44 = !{!"function", !"void", !40, i64 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, float poison, float poison, float poison, float poison, float poison, float poison, float poison, float poison}
!45 = !{!"function", !"void", !40, i32 poison}
!46 = !{!"function", !"void", i64 poison, !47}
!47 = !{i32 0, i8 poison}
