#version 450 core

layout(set = 0, binding = 0 ) uniform sampler2DMS       samp2DMS;
layout(set = 0, binding = 1 ) uniform sampler2DMSArray  samp2DMSA;

layout(set = 1, binding = 0) buffer BO
{
    int mOut;
};

void main()
{
    int temp = 0;

    temp += textureSamples(samp2DMS);
    temp += textureSamples(samp2DMSA);

    mOut = temp;
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call <8 x i32> {{.*}} @llpc.call.load.resource.desc.v8i32(i32 0, i32 0, i32 0, i1 false)
; SHADERTEST: call i32 @llpc.image.querynonlod.samples{{.*}}({{.*}},{{.*}})
; SHADERTEST: call <8 x i32> {{.*}} @llpc.call.load.resource.desc.v8i32(i32 0, i32 1, i32 0, i1 false)
; SHADERTEST: call i32 @llpc.image.querynonlod.samples{{.*}}({{.*}},{{.*}})

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
