#version 450 core

layout(set = 0, binding = 0,  rgba8)  uniform image1D img1D;
layout(set = 0, binding = 1,  rgba8)  uniform image2D img2D;
layout(set = 0, binding = 2,  rgba8)  uniform image3D img3D;
layout(set = 0, binding = 3,  rgba8)  uniform imageCube imgCube;
layout(set = 0, binding = 4,  rgba8)  uniform image2DRect imgRect;
layout(set = 0, binding = 5,  rgba8)  uniform image1DArray img1DA;
layout(set = 0, binding = 6,  rgba8)  uniform image2DArray img2DA;
layout(set = 0, binding = 7,  rgba8)  uniform imageCubeArray imgCubeA;
layout(set = 0, binding = 8,  rgba8)  uniform image2DMS img2DMS;
layout(set = 0, binding = 9,  rgba8)  uniform image2DMSArray img2DMSA;
layout(set = 0, binding = 10, rgba8)  uniform imageBuffer imgBuffer;

layout(set = 1, binding = 0) buffer BO
{
    int   mOut1;
    ivec2 mOut2;
    ivec3 mOut3;
};

void main()
{
    mOut1  = imageSize(img1D);
    mOut2  = imageSize(img2D);
    mOut3  = imageSize(img3D);

    mOut2 += imageSize(imgCube);
    mOut2 += imageSize(imgRect);
    mOut2 += imageSize(img1DA);
    mOut3 += imageSize(img2DA);
    mOut3 += imageSize(imgCubeA);
    mOut2 += imageSize(img2DMS);
    mOut3 += imageSize(img2DMSA);
    mOut1 += imageSize(imgBuffer);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 0
; SHADERTEST: call i32 @llpc.image.querynonlod.sizelod.1D.i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 1
; SHADERTEST: call <2 x i32> @llpc.image.querynonlod.sizelod.2D.v2i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 2
; SHADERTEST: call <3 x i32> @llpc.image.querynonlod.sizelod.3D.v3i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 3
; SHADERTEST: call <2 x i32> @llpc.image.querynonlod.sizelod.Cube.v2i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 4
; SHADERTEST: call <2 x i32> @llpc.image.querynonlod.sizelod.2D.v2i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 5
; SHADERTEST: call <2 x i32> @llpc.image.querynonlod.sizelod.1DArray.v2i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 6
; SHADERTEST: call <3 x i32> @llpc.image.querynonlod.sizelod.2DArray.v3i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 7
; SHADERTEST: call <3 x i32> @llpc.image.querynonlod.sizelod.CubeArray.v3i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 8
; SHADERTEST: call <2 x i32> @llpc.image.querynonlod.sizelod.2D.sample.v2i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 9
; SHADERTEST: call <3 x i32> @llpc.image.querynonlod.sizelod.2DArray.sample.v3i32{{.*}}({{.*}}, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.texel.buffer.desc.ptr{{.*}}(i32 0, i32 10
; SHADERTEST: call i32 @llpc.image.querynonlod.sizelod.Buffer.i32({{.*}}, i32 0,{{.*}})

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: call float @llvm.amdgcn.image.getresinfo.1d.f32.i32(i32 1, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <2 x float> @llvm.amdgcn.image.getresinfo.2d.v2f32.i32(i32 3, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <3 x float> @llvm.amdgcn.image.getresinfo.3d.v3f32.i32(i32 7, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <2 x float> @llvm.amdgcn.image.getresinfo.cube.v2f32.i32(i32 3, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <2 x float> @llvm.amdgcn.image.getresinfo.2d.v2f32.i32(i32 3, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <2 x float> @llvm.amdgcn.image.getresinfo.1darray.v2f32.i32(i32 3, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <3 x float> @llvm.amdgcn.image.getresinfo.2darray.v3f32.i32(i32 7, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.getresinfo.cube.v4f32.i32(i32 15, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <2 x float> @llvm.amdgcn.image.getresinfo.2dmsaa.v2f32.i32(i32 3, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <3 x float> @llvm.amdgcn.image.getresinfo.2darraymsaa.v3f32.i32(i32 7, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
