#version 450 core

layout(set = 0, binding = 0, rgba8) uniform image2D img2D;
layout(set = 0, binding = 1, rgba8) uniform image1D img1D;
layout(set = 0, binding = 2, rgba8) uniform image3D img3D;
layout(set = 0, binding = 3, rgba8) uniform image1DArray img1DArray;
layout(set = 0, binding = 4, rgba8) uniform image2DArray img2DArray;
layout(set = 0, binding = 5, rgba8) uniform image2DRect img2DRect;

layout(set = 1, binding = 0) buffer BO
{
    vec4 mOut;
};

void main()
{
    mOut  = imageLoad(img2D,        ivec2(0, 0));
    mOut += imageLoad(img1D,        0);
    mOut += imageLoad(img3D,        ivec3(0, 0, 0));
    mOut += imageLoad(img1DArray,   ivec2(0, 0));
    mOut += imageLoad(img2DArray,   ivec3(0, 0, 0));
    mOut += imageLoad(img2DRect,    ivec2(0, 0));
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 0
; SHADERTEST: call <4 x float> @llpc.image.read.f32.2D{{.*}}({{.*}}, <2 x i32> zeroinitializer, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 1
; SHADERTEST: call <4 x float> @llpc.image.read.f32.1D{{.*}}({{.*}}, i32 0, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 2
; SHADERTEST: call <4 x float> @llpc.image.read.f32.3D{{.*}}({{.*}}, <3 x i32> zeroinitializer, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 3
; SHADERTEST: call <4 x float> @llpc.image.read.f32.1DArray{{.*}}({{.*}}, <2 x i32> zeroinitializer, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 4
; SHADERTEST: call <4 x float> @llpc.image.read.f32.2DArray{{.*}}({{.*}}, <3 x i32> zeroinitializer, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 5
; SHADERTEST: call <4 x float> @llpc.image.read.f32.Rect{{.*}}({{.*}}, <2 x i32> zeroinitializer, i32 0,{{.*}})

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 0, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.1d.v4f32.i32(i32 15, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.3d.v4f32.i32(i32 15, i32 0, i32 0, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.1darray.v4f32.i32(i32 15, i32 0, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.2darray.v4f32.i32(i32 15, i32 0, i32 0, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.2d.v4f32.i32(i32 15, i32 0, i32 0,{{.*}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
