#version 450 core
#extension GL_AMD_shader_image_load_store_lod : enable

layout(set = 0, binding = 0,  r32i) uniform iimage1D        img1D;
layout(set = 0, binding = 1,  r32i) uniform iimage2D        img2D;
layout(set = 0, binding = 2,  r32i) uniform iimage3D        img3D;
layout(set = 0, binding = 3,  r32i) uniform iimageCube      imgCube;
layout(set = 0, binding = 4,  r32i) uniform iimage1DArray   img1DArray;
layout(set = 0, binding = 5,  r32i) uniform iimage2DArray   img2DArray;
layout(set = 0, binding = 6,  r32i) uniform iimageCubeArray imgCubeArray;

void main()
{
    ivec4 temp = ivec4(0);
    temp += imageLoadLodAMD(img1D,          9,              7);
    temp += imageLoadLodAMD(img2D,          ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img3D,          ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCube,        ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(img1DArray,     ivec2(9, 9),    7);
    temp += imageLoadLodAMD(img2DArray,     ivec3(9, 9, 9), 7);
    temp += imageLoadLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7);

    imageStoreLodAMD(img1D,          9,              7, temp);
    imageStoreLodAMD(img2D,          ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img3D,          ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCube,        ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(img1DArray,     ivec2(9, 9),    7, temp);
    imageStoreLodAMD(img2DArray,     ivec3(9, 9, 9), 7, temp);
    imageStoreLodAMD(imgCubeArray,   ivec3(9, 9, 9), 7, temp);
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -spvgen-dir=%spvgendir% -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST-LABEL: {{^// LLPC}}  SPIR-V lowering results
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 0
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.1D.lod{{.*}}({{.*}}, i32 9, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 1
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.2D.lod{{.*}}({{.*}}, <2 x i32> <i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 2
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.3D.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 3
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.Cube.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 4
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.1DArray.lod{{.*}}({{.*}}, <2 x i32> <i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 5
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.2DArray.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 6
; SHADERTEST: call <4 x i32> @llpc.image.read.i32.CubeArray.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 0
; SHADERTEST: call void @llpc.image.write.i32.1D.lod{{.*}}({{.*}}, i32 9,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 1
; SHADERTEST: call void @llpc.image.write.i32.2D.lod{{.*}}({{.*}}, <2 x i32> <i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 2
; SHADERTEST: call void @llpc.image.write.i32.3D.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 3
; SHADERTEST: call void @llpc.image.write.i32.Cube.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 4
; SHADERTEST: call void @llpc.image.write.i32.1DArray.lod{{.*}}({{.*}}, <2 x i32> <i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 5
; SHADERTEST: call void @llpc.image.write.i32.2DArray.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})
; SHADERTEST: call {{.*}} @"llpc.call.get.image.desc.ptr{{.*}}(i32 0, i32 6
; SHADERTEST: call void @llpc.image.write.i32.CubeArray.lod{{.*}}({{.*}}, <3 x i32> <i32 9, i32 9, i32 9>,{{.*}}, i32 7, i32 0,{{.*}})

; SHADERTEST-LABEL: {{^// LLPC}}  pipeline patching results
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.1d.v4f32.i32(i32 15, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.2d.v4f32.i32(i32 15, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.3d.v4f32.i32(i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.cube.v4f32.i32(i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.1darray.v4f32.i32(i32 15, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call <4 x float> @llvm.amdgcn.image.load.mip.2darray.v4f32.i32(i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.1d.v4f32.i32({{.*}}, i32 15, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.2d.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.3d.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.cube.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.1darray.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.2darray.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: call void @llvm.amdgcn.image.store.mip.cube.v4f32.i32({{.*}}, i32 15, i32 9, i32 9, i32 9, i32 7,{{.*}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
