#version 450

#extension GL_EXT_shader_explicit_arithmetic_types_int8: enable

#define SIZE 65536

layout(set = 0, binding = 0) buffer _ {
    int8_t a[SIZE];
};

void main() {
    for (int i = 0; i < SIZE; i++) {
        a[i] = int8_t(0);
    }
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST: call void @llvm.amdgcn.raw.buffer.store.i8(i8 0, <4 x i32> {{%[^,]+}}, i32 {{%[^,]+}}, i32 0, i32 0)
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
