#version 450

layout (local_size_x = 16, local_size_y = 16) in;

struct StrType {
    uint s1;
    uint sa1[gl_WorkGroupSize.x];
};

shared StrType str1;

uint g_ui;

void main()
{
    str1.s1 = gl_LocalInvocationID.x;
    str1.sa1[gl_LocalInvocationID.x] = str1.s1;

    g_ui = str1.sa1[gl_LocalInvocationID.x];
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -enable-opaque-pointers=true -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s

; SHADERTEST-LABEL: {{^// LLPC}} SPIRV-to-LLVM translation results
; SHADERTEST: @[[LDS:[^ ]*]] = addrspace(3) global { i32, [16 x i32] }
; SHADERTEST: store i32 %{{[0-9]*}}, ptr addrspace(3) @[[LDS]]
; SHADERTEST: %{{[0-9]*}} = load i32, ptr addrspace(3) @[[LDS]]

; SHADERTEST: %{{[0-9]*}} = getelementptr { i32, [16 x i32] }, ptr addrspace(3) @[[LDS]], i32 0, i32 1, i32 %{{[0-9]*}}
; SHADERTEST: store i32 %{{[0-9]*}}, ptr addrspace(3) %{{[0-9]*}}
; SHADERTEST: %{{[0-9]*}} = getelementptr { i32, [16 x i32] }, ptr addrspace(3) @{{.*}}, i32 0, i32 1, i32 %{{[0-9]*}}
; SHADERTEST: %{{[0-9]*}} = load i32, ptr addrspace(3) %{{[0-9]*}}

; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
