#version 450

#define SIZE 65536

layout(set = 0, binding = 0) buffer _ {
    int a[SIZE];
};

void main() {
    for (int i = 0; i < SIZE; i++) {
        a[i] = 0;
    }
}

// BEGIN_SHADERTEST
/*
; RUN: amdllpc -v %gfxip %s | FileCheck -check-prefix=SHADERTEST %s
; SHADERTEST-LABEL: {{^// LLPC}} pipeline patching results
; SHADERTEST-COUNT-32: call void @llvm.amdgcn.raw.buffer.store.i32(i32 0,
; SHADERTEST-LABEL: {{^// LLPC}} final pipeline module info
; SHADERTEST: AMDLLPC SUCCESS
*/
// END_SHADERTEST
