; NOTE: Assertions have been autogenerated by tool/update_llpc_test_checks.py UTC_ARGS: --tool lgc
; RUN: lgc -mcpu=gfx1010 -print-after=lgc-builder-replayer -o - %s 2>&1 | FileCheck --check-prefixes=CHECK %s
; ModuleID = 'lgcPipeline'
source_filename = "lgcPipeline"
target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8-p32:32:32"
target triple = "amdgcn--amdpal"

; Function Attrs: nounwind
define dllexport spir_func void @lgc.shader.FS.main() local_unnamed_addr #0 !spirv.ExecutionModel !22 !lgc.shaderstage !23 {
.entry:
  %0 = call ptr addrspace(4) (...) @lgc.create.load.push.constants.ptr.p4()
  %1 = call i32 (...) @lgc.create.read.generic.input.i32(i32 3, i32 0, i32 0, i32 0, i32 17, i32 poison)
  %2 = load i32, ptr addrspace(4) %0, align 4
  br label %3

3:                                                ; preds = %7, %.entry
  %.010 = phi <4 x float> [ zeroinitializer, %.entry ], [ %30, %7 ]
  %.09 = phi <4 x float> [ zeroinitializer, %.entry ], [ %28, %7 ]
  %.0 = phi i32 [ %2, %.entry ], [ %31, %7 ]
  %4 = getelementptr inbounds <{ i32, i32 }>, ptr addrspace(4) %0, i64 0, i32 1
  %5 = load i32, ptr addrspace(4) %4, align 4
  %6 = icmp slt i32 %.0, %5
  %cond.freeze = freeze i1 %6
  br i1 %cond.freeze, label %7, label %32

7:                                                ; preds = %3
  %8 = call ptr addrspace(4) (...) @lgc.create.get.desc.ptr.p4(i32 4, i32 4, i64 1, i32 12)
  %9 = call i32 (...) @lgc.create.get.desc.stride.i32(i32 4, i32 4, i64 1, i32 12)
  %10 = load <4 x i32>, ptr addrspace(4) %8, align 16, !invariant.load !24
  %11 = call <4 x i32> (...) @lgc.create.image.load.v4i32(i32 0, i32 1536, <4 x i32> %10, i32 %.0)
  %12 = extractelement <4 x i32> %11, i64 0
  %13 = call ptr addrspace(4) (...) @lgc.create.get.desc.ptr.p4(i32 1, i32 1, i64 0, i32 6)
  %14 = call i32 (...) @lgc.create.get.desc.stride.i32(i32 1, i32 1, i64 0, i32 6)
  %15 = mul i32 %12, %14
  %16 = sext i32 %15 to i64
  %17 = getelementptr i8, ptr addrspace(4) %13, i64 %16
  %18 = load <8 x i32>, ptr addrspace(4) %17, align 32, !invariant.load !24
  %19 = call ptr addrspace(4) (...) @lgc.create.get.desc.ptr.p4(i32 2, i32 2, i64 0, i32 5)
  %20 = load <4 x i32>, ptr addrspace(4) %19, align 16, !invariant.load !24
  %21 = call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.sample.v4f32(i32 1, i32 24, <8 x i32> %18, <4 x i32> %20, i32 1, <2 x float> zeroinitializer)
  %22 = mul i32 %1, %14
  %23 = sext i32 %22 to i64
  %24 = getelementptr i8, ptr addrspace(4) %13, i64 %23
  %25 = load <8 x i32>, ptr addrspace(4) %24, align 32, !invariant.load !24
  %26 = call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.sample.v4f32(i32 1, i32 24, <8 x i32> %25, <4 x i32> %20, i32 1, <2 x float> zeroinitializer)
  %27 = call reassoc nnan nsz arcp contract afn <4 x float> (...) @lgc.create.image.sample.v4f32(i32 1, i32 24, <8 x i32> %18, <4 x i32> %20, i32 1, <2 x float> zeroinitializer)
  %28 = fadd reassoc nnan nsz arcp contract afn <4 x float> %.09, %27
  %29 = fadd reassoc nnan nsz arcp contract afn <4 x float> %21, %26
  %30 = fadd reassoc nnan nsz arcp contract afn <4 x float> %.010, %29
  %31 = add i32 %.0, 1
  br label %3, !llvm.loop !25

32:                                               ; preds = %3
  ret void
}

; Function Attrs: nounwind willreturn memory(read)
declare ptr addrspace(4) @lgc.create.load.push.constants.ptr.p4(...) local_unnamed_addr #1

; Function Attrs: nounwind willreturn memory(read)
declare i32 @lgc.create.read.generic.input.i32(...) local_unnamed_addr #1

; Function Attrs: nounwind memory(none)
declare ptr addrspace(4) @lgc.create.get.desc.ptr.p4(...) local_unnamed_addr #2

; Function Attrs: nounwind memory(none)
declare i32 @lgc.create.get.desc.stride.i32(...) local_unnamed_addr #2

; Function Attrs: nounwind willreturn memory(read)
declare <4 x i32> @lgc.create.image.load.v4i32(...) local_unnamed_addr #1

; Function Attrs: nounwind willreturn memory(read)
declare <4 x float> @lgc.create.image.sample.v4f32(...) local_unnamed_addr #1

attributes #0 = { nounwind "denormal-fp-math-f32"="preserve-sign" }
attributes #1 = { nounwind willreturn memory(read) }
attributes #2 = { nounwind memory(none) }

!lgc.client = !{!0}
!lgc.options = !{!1}
!lgc.options.VS = !{!2}
!lgc.options.FS = !{!3}
!lgc.user.data.nodes = !{!4, !5, !6, !7, !8, !9, !10, !11, !12, !13, !14, !15}
!lgc.vertex.inputs = !{!16, !17, !18}
!lgc.color.export.formats = !{!19}
!lgc.rasterizer.state = !{!20}
!amdgpu.pal.metadata.msgpack = !{!21}

!0 = !{!"Vulkan"}
!1 = !{i32 1397006593, i32 1762399868, i32 679484448, i32 1745956893, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 272, i32 0, i32 0, i32 1, i32 256, i32 256, i32 -1, i32 0, i32 0, i32 0, i32 0, i32 0, i32 1, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 16777216}
!2 = !{i32 1156202838, i32 -1602642692, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 64, i32 0, i32 0, i32 3, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 20, i32 1800, i32 0, i32 0, i32 1}
!3 = !{i32 -1603553139, i32 446675175, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 64, i32 0, i32 0, i32 3, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 20, i32 1800, i32 0, i32 0, i32 1}
!4 = !{!"IndirectUserDataVaPtr", i32 8, i32 2, i32 0, i32 1, i32 4}
!5 = !{!"DescriptorTableVaPtr", i32 7, i32 66, i32 11, i32 1, i32 3}
!6 = !{!"DescriptorBufferCompact", i32 10, i32 66, i32 0, i32 2, i64 93, i32 17, i32 2}
!7 = !{!"DescriptorBuffer", i32 6, i32 66, i32 2, i32 4, i64 93, i32 0, i32 4}
!8 = !{!"DescriptorBuffer", i32 6, i32 66, i32 6, i32 4, i64 93, i32 1, i32 4}
!9 = !{!"StreamOutTableVaPtr", i32 11, i32 4, i32 3, i32 1, i32 0}
!10 = !{!"PushConst", i32 9, i32 66, i32 7, i32 2, i64 4294967295, i32 0, i32 4}
!11 = !{!"DescriptorTableVaPtr", i32 7, i32 66, i32 9, i32 1, i32 2}
!12 = !{!"DescriptorSampler", i32 2, i32 66, i32 0, i32 4, i64 0, i32 5, i32 4}
!13 = !{!"DescriptorResource", i32 1, i32 66, i32 4, i32 32768, i64 0, i32 6, i32 8}
!14 = !{!"DescriptorTableVaPtr", i32 7, i32 66, i32 10, i32 1, i32 1}
!15 = !{!"DescriptorTexelBuffer", i32 4, i32 66, i32 0, i32 4, i64 1, i32 12, i32 4}
!16 = !{i32 0, i32 0, i32 0, i32 40, i32 14, i32 7}
!17 = !{i32 1, i32 0, i32 16, i32 40, i32 11, i32 7}
!18 = !{i32 2, i32 0, i32 24, i32 40, i32 14, i32 5}
!19 = !{i32 14, i32 7, i32 0, i32 0, i32 15}
!20 = !{i32 0, i32 0, i32 0, i32 1}
!21 = !{!"\82\B0amdpal.pipelines\91\83\B0.spill_threshold\CD\FF\FF\B0.user_data_limit\00\AF.xgl_cache_info\82\B3.128_bit_cache_hash\92\CF\9BN7\81A[\8A\DB\CF\9Daz\E2A\8F\88\AD\AD.llpc_version\A470.1\AEamdpal.version\92\03\00"}
!22 = !{i32 4}
!23 = !{i32 6}
!24 = !{}
!25 = distinct !{!25}
; CHECK-LABEL: @lgc.shader.FS.main(
; CHECK-NEXT:  .entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.amdgcn.s.getpc()
; CHECK-NEXT:    [[TMP1:%.*]] = bitcast i64 [[TMP0]] to <2 x i32>
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.amdgcn.s.getpc()
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast i64 [[TMP2]] to <2 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = call i64 @llvm.amdgcn.s.getpc()
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast i64 [[TMP4]] to <2 x i32>
; CHECK-NEXT:    [[TMP6:%.*]] = call ptr addrspace(4) @lgc.user.data(i32 28)
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 (...) @lgc.input.import.interpolated.i32(i1 false, i32 3, i32 0, i32 0, i32 poison, i32 1, i32 poison)
; CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr addrspace(4) [[TMP6]], align 4
; CHECK-NEXT:    br label [[TMP9:%.*]]
; CHECK:       9:
; CHECK-NEXT:    [[DOT010:%.*]] = phi <4 x float> [ zeroinitializer, [[DOTENTRY:%.*]] ], [ [[TMP67:%.*]], [[TMP13:%.*]] ]
; CHECK-NEXT:    [[DOT09:%.*]] = phi <4 x float> [ zeroinitializer, [[DOTENTRY]] ], [ [[TMP65:%.*]], [[TMP13]] ]
; CHECK-NEXT:    [[DOT0:%.*]] = phi i32 [ [[TMP8]], [[DOTENTRY]] ], [ [[TMP68:%.*]], [[TMP13]] ]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <{ i32, i32 }>, ptr addrspace(4) [[TMP6]], i64 0, i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr addrspace(4) [[TMP10]], align 4
; CHECK-NEXT:    [[TMP12:%.*]] = icmp slt i32 [[DOT0]], [[TMP11]]
; CHECK-NEXT:    [[COND_FREEZE:%.*]] = freeze i1 [[TMP12]]
; CHECK-NEXT:    br i1 [[COND_FREEZE]], label [[TMP13]], label [[TMP69:%.*]]
; CHECK:       13:
; CHECK-NEXT:    [[TMP14:%.*]] = call i32 @lgc.load.user.data.i32(i32 40)
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <2 x i32> [[TMP5]], i32 [[TMP14]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = bitcast <2 x i32> [[TMP15]] to i64
; CHECK-NEXT:    [[TMP17:%.*]] = inttoptr i64 [[TMP16]] to ptr addrspace(4)
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP17]], i32 0
; CHECK-NEXT:    [[TMP19:%.*]] = load <4 x i32>, ptr addrspace(4) [[TMP18]], align 16, !invariant.load !24
; CHECK-NEXT:    [[TMP20:%.*]] = call <4 x i32> @llvm.amdgcn.struct.buffer.load.format.v4i32(<4 x i32> [[TMP19]], i32 [[DOT0]], i32 0, i32 0, i32 0), !invariant.load !24
; CHECK-NEXT:    [[TMP21:%.*]] = extractelement <4 x i32> [[TMP20]], i64 0
; CHECK-NEXT:    [[TMP22:%.*]] = call i32 @lgc.load.user.data.i32(i32 36)
; CHECK-NEXT:    [[TMP23:%.*]] = insertelement <2 x i32> [[TMP3]], i32 [[TMP22]], i64 0
; CHECK-NEXT:    [[TMP24:%.*]] = bitcast <2 x i32> [[TMP23]] to i64
; CHECK-NEXT:    [[TMP25:%.*]] = inttoptr i64 [[TMP24]] to ptr addrspace(4)
; CHECK-NEXT:    [[TMP26:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP25]], i32 16
; CHECK-NEXT:    [[TMP27:%.*]] = mul i32 [[TMP21]], 32
; CHECK-NEXT:    [[TMP28:%.*]] = sext i32 [[TMP27]] to i64
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP26]], i64 [[TMP28]]
; CHECK-NEXT:    [[TMP30:%.*]] = load <8 x i32>, ptr addrspace(4) [[TMP29]], align 32, !invariant.load !24
; CHECK-NEXT:    [[TMP31:%.*]] = call i32 @lgc.load.user.data.i32(i32 36)
; CHECK-NEXT:    [[TMP32:%.*]] = insertelement <2 x i32> [[TMP1]], i32 [[TMP31]], i64 0
; CHECK-NEXT:    [[TMP33:%.*]] = bitcast <2 x i32> [[TMP32]] to i64
; CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i64 [[TMP33]] to ptr addrspace(4)
; CHECK-NEXT:    [[TMP35:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP34]], i32 0
; CHECK-NEXT:    [[TMP36:%.*]] = load <4 x i32>, ptr addrspace(4) [[TMP35]], align 16, !invariant.load !24
; CHECK-NEXT:    [[TMP37:%.*]] = call i32 @llvm.amdgcn.waterfall.begin.i32(i32 0, i32 [[TMP27]])
; CHECK-NEXT:    [[TMP38:%.*]] = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(i32 [[TMP37]], i32 [[TMP27]])
; CHECK-NEXT:    [[TMP39:%.*]] = sext i32 [[TMP38]] to i64
; CHECK-NEXT:    [[TMP40:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP26]], i64 [[TMP39]]
; CHECK-NEXT:    [[TMP41:%.*]] = load <8 x i32>, ptr addrspace(4) [[TMP40]], align 32, !invariant.load !24
; CHECK-NEXT:    [[TMP42:%.*]] = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(i32 [[TMP37]], <4 x i32> [[TMP36]])
; CHECK-NEXT:    [[TMP43:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> [[TMP41]], <4 x i32> [[TMP42]], i1 false, i32 0, i32 0)
; CHECK-NEXT:    [[TMP44:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.waterfall.end.v4f32(i32 [[TMP37]], <4 x float> [[TMP43]])
; CHECK-NEXT:    [[TMP45:%.*]] = mul i32 [[TMP7]], 32
; CHECK-NEXT:    [[TMP46:%.*]] = sext i32 [[TMP45]] to i64
; CHECK-NEXT:    [[TMP47:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP26]], i64 [[TMP46]]
; CHECK-NEXT:    [[TMP48:%.*]] = load <8 x i32>, ptr addrspace(4) [[TMP47]], align 32, !invariant.load !24
; CHECK-NEXT:    [[TMP49:%.*]] = call i32 @llvm.amdgcn.waterfall.begin.i32(i32 0, i32 [[TMP45]])
; CHECK-NEXT:    [[TMP50:%.*]] = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(i32 [[TMP49]], i32 [[TMP45]])
; CHECK-NEXT:    [[TMP51:%.*]] = sext i32 [[TMP50]] to i64
; CHECK-NEXT:    [[TMP52:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP26]], i64 [[TMP51]]
; CHECK-NEXT:    [[TMP53:%.*]] = load <8 x i32>, ptr addrspace(4) [[TMP52]], align 32, !invariant.load !24
; CHECK-NEXT:    [[TMP54:%.*]] = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(i32 [[TMP49]], <4 x i32> [[TMP36]])
; CHECK-NEXT:    [[TMP55:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> [[TMP53]], <4 x i32> [[TMP54]], i1 false, i32 0, i32 0)
; CHECK-NEXT:    [[TMP56:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.waterfall.end.v4f32(i32 [[TMP49]], <4 x float> [[TMP55]])
; CHECK-NEXT:    [[TMP57:%.*]] = call i32 @llvm.amdgcn.waterfall.begin.i32(i32 0, i32 [[TMP27]])
; CHECK-NEXT:    [[TMP58:%.*]] = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(i32 [[TMP57]], i32 [[TMP27]])
; CHECK-NEXT:    [[TMP59:%.*]] = sext i32 [[TMP58]] to i64
; CHECK-NEXT:    [[TMP60:%.*]] = getelementptr i8, ptr addrspace(4) [[TMP26]], i64 [[TMP59]]
; CHECK-NEXT:    [[TMP61:%.*]] = load <8 x i32>, ptr addrspace(4) [[TMP60]], align 32, !invariant.load !24
; CHECK-NEXT:    [[TMP62:%.*]] = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(i32 [[TMP57]], <4 x i32> [[TMP36]])
; CHECK-NEXT:    [[TMP63:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> [[TMP61]], <4 x i32> [[TMP62]], i1 false, i32 0, i32 0)
; CHECK-NEXT:    [[TMP64:%.*]] = call reassoc nnan nsz arcp contract afn <4 x float> @llvm.amdgcn.waterfall.end.v4f32(i32 [[TMP57]], <4 x float> [[TMP63]])
; CHECK-NEXT:    [[TMP65]] = fadd reassoc nnan nsz arcp contract afn <4 x float> [[DOT09]], [[TMP64]]
; CHECK-NEXT:    [[TMP66:%.*]] = fadd reassoc nnan nsz arcp contract afn <4 x float> [[TMP44]], [[TMP56]]
; CHECK-NEXT:    [[TMP67]] = fadd reassoc nnan nsz arcp contract afn <4 x float> [[DOT010]], [[TMP66]]
; CHECK-NEXT:    [[TMP68]] = add i32 [[DOT0]], 1
; CHECK-NEXT:    br label [[TMP9]], !llvm.loop [[LOOP25:![0-9]+]]
; CHECK:       69:
; CHECK-NEXT:    ret void
;
