#!/bin/sh
##
 #######################################################################################################################
 #
 #  Copyright (c) 2025 Advanced Micro Devices, Inc. All Rights Reserved.
 #
 #  Permission is hereby granted, free of charge, to any person obtaining a copy
 #  of this software and associated documentation files (the "Software"), to
 #  deal in the Software without restriction, including without limitation the
 #  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 #  sell copies of the Software, and to permit persons to whom the Software is
 #  furnished to do so, subject to the following conditions:
 #
 #  The above copyright notice and this permission notice shall be included in all
 #  copies or substantial portions of the Software.
 #
 #  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 #  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 #  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 #  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 #  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 #  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 #  IN THE SOFTWARE.
 #
 #######################################################################################################################
# A pre-commit hook to prevent a commit if clang-format has not yet
# been applied. This usually leads to a preventable failure in CI.

CLANG_FORMAT_VERSION=14
CLANG_FORMAT_DIFF_EXECUTABLE="clang-format-diff-$CLANG_FORMAT_VERSION"

if ! command -v ${CLANG_FORMAT_DIFF_EXECUTABLE} 2>&1 > /dev/null ; then
    echo "Specific ${CLANG_FORMAT_DIFF_EXECUTABLE} does not exist."
    CLANG_FORMAT_DIFF_EXECUTABLE="clang-format-diff"
    echo "Trying ${CLANG_FORMAT_DIFF_EXECUTABLE} as fallback instead."
    if ! command -v ${CLANG_FORMAT_DIFF_EXECUTABLE} 2>&1 > /dev/null ; then
        echo "${CLANG_FORMAT_DIFF_EXECUTABLE} does not exist. Aborting."
        exit 0
    fi
fi

FORMAT_FILE=$(mktemp /tmp/formatted-diff-XXXXXX.diff)

# Check whether any of the changes would be re-formatted.
git diff HEAD -U0 --no-color -- '**/*.cpp' '**/*.cc' '**/*.h' '**/*.hh' | ${CLANG_FORMAT_DIFF_EXECUTABLE} -p1 > $FORMAT_FILE

if ! grep -q '[^[:space:]]' ${FORMAT_FILE} ; then
    echo "The code is properly formatted."
else
    echo "The code was not properly formatted. Please re-run git-clang-format. You can use the diff in ${FORMAT_FILE} as git patch."
    echo "Diff:"
    cat $FORMAT_FILE
    exit 1
fi
