/*
 ***********************************************************************************************************************
 *
 *  Copyright (c) 2024-2025 Advanced Micro Devices, Inc. All Rights Reserved.
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to
 *  deal in the Software without restriction, including without limitation the
 *  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 *  sell copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 *  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 *  IN THE SOFTWARE.
 *
 **********************************************************************************************************************/

// RUN: amdllpc -gfxip 11.0 -filetype=asm -o - %s | FileCheck -check-prefix=GFX11 %s

// TODO: Should use v_readlane

// GFX11: v_permlane64_b32
// GFX11: ds_bpermute_b32
// GFX11: ds_bpermute_b32

#version 450
#extension GL_KHR_shader_subgroup_shuffle : enable

layout(local_size_x = 32) in;

layout(push_constant) uniform constants {
    uint lane;
};

layout(set = 0, binding = 0, std430) buffer InBuffer {
    int a[32];
} inbuf;

layout(set = 0, binding = 1, std430) buffer OutBuffer {
    int b[32];
} outbuf;

void main() {
    uint id = gl_SubgroupInvocationID;
    int x = inbuf.a[id];
    x = subgroupShuffle(x, lane);
    outbuf.b[id] = x;
}
