name: Static code check

on:
  pull_request:

jobs:
  cppcheck:
    name: cppcheck
    runs-on: "ubuntu-20.04"
    steps:
      - name: Setup environment
        run: |
          sudo apt-get install -yqq cppcheck
      - name: Checkout LLPC
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY}.git .
          git fetch origin +${GITHUB_SHA}:${GITHUB_REF} --update-head-ok
          git checkout ${GITHUB_SHA}
          git submodule update --init
      - name: Run cppcheck
        run: |
          cppcheck -q -j$(( $(nproc) * 4 )) --error-exitcode=1 --std=c++17 --inline-suppr . \
              -I imported/llvm-dialects/include
